'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Auto_Mgmt.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property backimg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimg9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimg9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property circle_cropped_2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("circle-cropped(2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property d7d1f3a122fa1930b2de5c409aa1abe8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d7d1f3a122fa1930b2de5c409aa1abe8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hero_bike_spare_parts_500x500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hero-bike-spare-parts-500x500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageonline_co_cropped_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageonline-co-cropped-image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageonline_co_cropped_image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageonline-co-cropped-image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kisspng_login_affiliate_marketing_email_password_icon_gold_keys_and_locks_5a94a582489de7_2426834315196911382975() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-login-affiliate-marketing-email-password-icon-gold-keys-and-locks-5a94a58"& _ 
                        "2489de7.2426834315196911382975", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kisspng_login_affiliate_marketing_email_password_icon_gold_keys_and_locks_5a94a582489de71() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-login-affiliate-marketing-email-password-icon-gold-keys-and-locks-5a94a58"& _ 
                        "2489de71", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
